version: "3.5"

services:

  noip:
    image: mumanski/no-ip:latest
    container_name: noip
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - noip:/config
    environment:
      USERNAME: "${NOIP_USERNAME}"
      PASSWORD: "${NOIP_PASSWORD}"
      DOMAINS: "${NOIP_DOMAINS}"
      INTERVAL: "${NOIP_INTERVAL}"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - pihole:/etc/pihole'
      - pihole_dnsmasq:/etc/dnsmasq.d'
    environment:
      TZ: "${GENERAL_TIMEZONE}"
      WEBPASSWORD: "${PIHOLE_PASSWORD}"

  openvpn:
    image: alekslitvinenk/openvpn
    container_name: openvpn
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn:/opt/Dockovpn_data
    environment:
      HOST_ADDR: "${OPENVPN_DOMAIN_ADDRESS}"
    cap_add:
      - NET_ADMIN

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      USERID: '1000'
      GROUPID: '1000'
      TZ: "${GENERAL_TIMEZONE}"
    tmpfs:
      - /tmp
    volumes:
      - ${SAMBA_MOUNT_PATH}:/mnt:z
    command: '-s "homeserver;/mnt;yes;no;no;${SAMBA_USERNAME}" -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" -p'

volumes:
  pihole:
  pihole_dnsmasq:
  noip:
  openvpn: